//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightNovelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ID_Chapter { get; set; }
        public Nullable<int> ID_Novel { get; set; }
        public Nullable<int> Chapter { get; set; }
        public string Name_Chapter { get; set; }
        public string Content1 { get; set; }
    
        public virtual Novel Novel { get; set; }
    }
}
