//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightNovelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Novel()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public int ID_Novel { get; set; }
        public string Name_NoveL { get; set; }
        public string Avatar { get; set; }
        public string Category { get; set; }
        public string Author { get; set; }
        public string Desc { get; set; }
        public Nullable<System.DateTime> DateUp { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Rate_Count { get; set; }
        public Nullable<int> View_Count { get; set; }
        public Nullable<int> BookMarked_Count { get; set; }
        public Nullable<int> Qty_Chapters { get; set; }
        public Nullable<System.DateTime> DateMod { get; set; }
        public Nullable<System.DateTime> DatePub { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
    }
}
